(in-package :cl-hdf5)

(defvar +hdf5-types+ `(:c-s1 ,+h5t-c-s1+
                       :fortran-s1 ,+h5t-fortran-s1+
                       :ieee-f32be ,+h5t-ieee-f32be+
                       :ieee-f32le ,+h5t-ieee-f32le+
                       :ieee-f64be ,+h5t-ieee-f64be+
                       :ieee-f64le ,+h5t-ieee-f64le+
                       :b8 ,+h5t-native-b8+
                       :b16 ,+h5t-native-b16+
                       :b32 ,+h5t-native-b32+
                       :b64 ,+h5t-native-b64+
                       :char ,+h5t-native-char+
                       :float ,+h5t-native-float+
                       :double ,+h5t-native-float+
                       :haddr ,+h5t-native-haddr+
                       :hbool ,+h5t-native-hbool+
                       :herr ,+h5t-native-herr+
                       :hsize ,+h5t-native-hsize+
                       :hssize ,+h5t-native-hssize+
                       :int ,+h5t-native-int+
                       :llong ,+h5t-native-llong+
                       :long ,+h5t-native-long+
                       :opaque ,+h5t-native-opaque+
                       :schar ,+h5t-native-schar+
                       :short ,+h5t-native-short+
                       :uchar ,+h5t-native-uchar+
                       :uint ,+h5t-native-uint+
                       :ulong ,+h5t-native-ulong+
                       :ullong ,+h5t-native-ullong+
                       :ushort ,+h5t-native-ushort+
                       :ncset ,+h5t-ncset+
                       :nstr ,+h5t-nstr+
                       :opaque-tag-max ,+h5t-opaque-tag-max+
                       :std-b8be ,+h5t-std-b8be+
                       :std-b8le ,+h5t-std-b8le+
                       :std-b16be ,+h5t-std-b16be+
                       :std-b16le ,+h5t-std-b16le+
                       :std-b32be ,+h5t-std-b32be+
                       :std-b32le ,+h5t-std-b32le+
                       :std-b64be ,+h5t-std-b64be+
                       :std-b64le ,+h5t-std-b64le+
                       :std-i8be ,+h5t-std-i8be+
                       :std-i8le ,+h5t-std-i8le+
                       :std-i16be ,+h5t-std-i16be+
                       :std-i16le ,+h5t-std-i16le+
                       :std-i32be ,+h5t-std-i32be+
                       :std-i32le ,+h5t-std-i32le+
                       :std-i64be ,+h5t-std-i64be+
                       :std-i64le ,+h5t-std-i64le+
                       :std-ref-dsetreg ,+h5t-std-ref-dsetreg+
                       :std-ref-obj ,+h5t-std-ref-obj+
                       :std-u8be ,+h5t-std-u8be+
                       :std-u8le ,+h5t-std-u8le+
                       :std-u16be ,+h5t-std-u16be+
                       :std-u16le ,+h5t-std-u16le+
                       :std-u32be ,+h5t-std-u32be+
                       :std-u32le ,+h5t-std-u32le+
                       :std-u64be ,+h5t-std-u64be+
                       :std-u64le ,+h5t-std-u64le+
                       :unix-d32be ,+h5t-unix-d32be+
                       :unix-d32le ,+h5t-unix-d32le+
                       :unix-d64be ,+h5t-unix-d64be+
                       :unix-d64le ,+h5t-unix-d64le+
                       :variable ,+h5t-variable+))

